config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :pools

  get '/pools/:id/bookings/new', to: 'bookings#new', as: 'new_pool_booking'
  post '/pools/:id/bookings', to: 'bookings#create', as: 'pool_bookings'
  get '/mypools', to: 'pools#mypools', as: 'my_pools'
  get '/mybookings', to: 'bookings#mybookings', as: 'my_bookings'
  patch '/bookings/:id/update_status', to: 'bookings#update_status', as: 'update_booking_status'

  resources :bookings do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pool
  has_many :reviews, dependent: :destroy

  enum status: { pending: 0, accepted: 1, rejected: 2 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo

  validates :address, presence: true, uniqueness: true, length: { minimum: 8 }
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 16 }
  validates :capacity, length: { in: 1..50 }, presence: true
  validates :price, presence: true # numericality: true, format: { with: /A\d{1,4}(\.\d{0,2})?z/ }
  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: :address,
    using: {
      tsearch: { prefix: true }
    }
  pg_search_scope :search_by_capacity,
    against: :capacity,
    using: {
      tsearch: { prefix: true }
    }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :pools, dependent: :destroy
  has_many :notifications
  has_many :reviews, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_pool, only: %i[new create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.pool = @pool
    @booking.user = current_user
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def mybookings
    @bookings = Booking.all
    @mybookings = @bookings.where(user_id: current_user)
  end

  def update_status
    @booking = Booking.find(params[:id])
    @booking.update(status: params[:status])
    redirect_to my_pools_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :user_id, :id, :status)
  end

  def find_pool
    @pool = Pool.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @pools = Pool.limit(12)
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_pool, only: %i[edit update destroy]

  def index
    @pools = Pool.all
    if params[:location].present? || params[:capacity].present?
      @pools = @pools.search_by_address(params[:location]) if params[:location].present?
      @pools = @pools.search_by_capacity(params[:capacity]) if params[:capacity].present?
    end
  end

  def show
    @pool = Pool.find(params[:id])
    @marker = [lat: @pool.latitude, lng: @pool.longitude]
  end

  def new
    @pool = Pool.new
  end

  def mypools
    @mypools = Pool.where(user_id: current_user)
    @bookingrequests = Booking.includes(:pool).where(user_id: current_user, status: 'pending')
    @allbookings = Booking.includes(:pool).where(user_id: current_user, status: 'accepted')
  end

  def create
    @pool = Pool.new(pool_params)
    @pool.user = current_user
    if @pool.save
      redirect_to my_pools_path status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pool
  end

  def update
    if @pool.update(pool_params)
      redirect_to my_pools_path, notice: 'Pool was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy
    redirect_to my_pools_path, notice: 'Pool was successfully destroyed.'
  end

  private

  def set_pool
    @pool = Pool.find(params[:id])
  end

  def pool_params
    params.require(:pool).permit(:address, :user_id, :title, :description, :price, :capacity, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_booking, only: %i[new create]
  before_action :find_review, only: %i[edit update destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to my_bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @review.update(review_params)
    redirect_to my_bookings_path
  end

  def destroy
    @review.destroy
    redirect_to my_bookings_path, status: :see_other
  end

  private

  def find_review
    @review = Review.find(params[:id])
  end

  def find_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/mybookings.html.erb
<div class="container">
  <div class="row g-0">
    <div class="d-flex justify-content-between my-4">
      <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't created any bookings!" if @mybookings.empty? %></em></small></span>
    </div>
  <% @mybookings.each do |booking| %>
    <div class="col-12 col-sm-12 col-md-6 col-lg-6">
      <div class="card-booking-ryan">
        <img src="<%= cl_image_path booking.pool.photo.key, height: 300, crop: :fill unless booking.pool.photo.key.blank?%>" />
        <div class="card-booking-infos-ryan">
          <div class="booking-header-div p-3"><h2><%= booking.pool.title %></h2></div>
          <div class="view-starttime paddingable">
            <h6>Owned by: <strong><%= booking.pool.user.first_name %> <%= booking.pool.user.last_name %></strong></h6>
            <div><p>Start time:</p>
            <p><%= booking.start_time.strftime("%B %d, %Y %I:%M %p") %></p></div>
          </div>
          <div class="author-endtime paddingable">
            <%= link_to "View pool", booking.pool, class: "booking-view-pool" %>
            <div><p>End time:</p>
            <p><%= booking.end_time.strftime("%B %d, %Y %I:%M %p") %></p></div>
          </div>
          <div class="review-price border-top paddingable">
            <% review = Review.find_by(booking_id: booking.id) %>
            <% if review.present? %>
              <div class="p-2"><h2> Your review of <%= booking.pool.title %>: </h2>
              <h6> <%= review.title %> </h6>
              <p> <%= review.content %> </p>
              <p> Rating: <% review.rating.times do %>
              <i class="fas fa-star star-blue"></i>
            <% end %> </p>
              <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small> </div>
              <%= link_to "Edit", edit_review_path(review), class: "booking-card-edit" %>
              <%= link_to "Delete", review_path(review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "booking-card-delete" %>
            <% else %>
              <% if booking.end_time < Time.current %>
                <%= link_to "Write a Review", new_booking_review_path(booking), class: "booking-view-pool" %>
              <% else %>
                <p><em> You can write a review after the booking ends </em></p>
              <% end %>
            <% end %>
            <h2 class="card-pool-pricing p-3">Cost: £<%= '%.2f' % ((booking.pool.price / 60) * ((booking.end_time - booking.start_time) / 60)).round(2) %></h2>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5 d-flex justify-content-center">
  <div class="form rounded p-3 shadow">
    <h3>Request Booking:</h3>
    <%= simple_form_for [@pool, @booking] do |f| %>
      <%= f.input :start_time %>
      <%= f.input :end_time %>
      <%= f.submit class: 'btn-form' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPnP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="footer-fix">
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <div class="content custom-min-height">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="button-container">
      <%= link_to "Browse all pools", pools_path, class: 'btn' %>
      <%= link_to "List a pool", new_pool_path, class: 'btn' %>
    </div>
      <%= render 'shared/pool_card' %>
  </div>
</div>

app/views/pools/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="form mary rounded p-3 shadow">
        <h3>Edit Pool:</h3>
        <%= simple_form_for @pool, url: pool_path(@pool), method: :patch do |f| %>
          <%= f.input :title, placeholder: 'Your pool name' %>
          <%= f.input :description, placeholder: 'Describe your pool', hint: 'Min 16 characters.' %>
          <%= f.input :address, placeholder: 'Your pool address' %>
          <div class="row">
            <div class="col-6">
              <%= f.input :price, as: :float, hint: 'eg. 89.59', label: 'Price per hour' %>
            </div>
            <div class="col-6">
              <%= f.input :capacity, collection: 1..20 %>
            </div>
          </div>
          <%= f.input :photo, as: :file %>
          <%= f.submit 'Update Pool', class: 'btn-form' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pools/index.html.erb
<div class="container">
  <%= render 'shared/pool_card' %>
</div>

app/views/pools/mypools.erb
<div class="container custom-min-height">
  <div class="d-flex justify-content-end">
    <%= link_to "List a pool", new_pool_path, class: "btn btn-success" %>
  </div>

  <%# my booking requests section %>
  <div class="row g-0 mb-5">
    <h2>Booking requests</h2>
    <% if @bookingrequests.empty? %>
       <em class="text-muted">You don't have any pending booking requests!</em>
    <% end %>
    <%= render "shared/booking_card", bookings: @bookingrequests %>
  </div>

    <%# all bookings section %>
  <div class="row g-0 mb-5">
    <h2>All bookings</h2>
    <% if @allbookings.empty? %>
       <em class="text-muted">You don't have any accepted bookings!</em>
    <% end %>
    <%= render "shared/booking_card", bookings: @allbookings %>
  </div>

  <%# my pools section %>
  <div class="row g-0">
    <h2>My pools</h2>
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't created any pools!" if @mypools.empty? %></em></small></span>
    <% @mypools.each do |pool| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card-pool">
          <img src="https://housing.com/news/wp-content/uploads/2023/03/10-Vastu-based-swimming-pool-ideas-for-home-construction-09.png" />
          <div class="card-pool-infos">
            <div>
              <h2><%= pool.title %></h2>
              <p><%= pool.description %></p>
            </div>
            <h2 class="card-pool-pricing">£<%= pool.price %></h2>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton<%= pool.id %>" data-bs-toggle="dropdown" aria-expanded="false">
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton<%= pool.id %>">
                <li> <%= link_to "View", pool_path(pool), class: "dropdown-item" %> </li>
                <li><a class="dropdown-item" href="<%= edit_pool_path(pool) %>">Edit</a></li>
                <li><%= link_to "Delete", pool_path(pool), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "dropdown-item" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pools/mypools.html.erb
<div class="container custom-min-height">
  <div class="d-flex justify-content-end">
    <%= link_to "List a pool", new_pool_path, class: 'btn list-a-pool-button' %>
  </div>

  <%# my booking requests section %>
  <div class="row g-0 mb-5">
    <h2>Booking requests</h2>
    <% if @bookingrequests.empty? %>
       <em class="text-muted">You don't have any pending booking requests!</em>
    <% end %>
    <%= render "shared/booking_card", bookings: @bookingrequests %>
  </div>

    <%# all bookings section %>
  <div class="row g-0 mb-5">
    <h2>All bookings</h2>
    <% if @allbookings.empty? %>
       <em class="text-muted">You don't have any accepted bookings!</em>
    <% end %>
    <%= render "shared/booking_card", bookings: @allbookings %>
  </div>

  <%# my pools section %>
  <div class="row g-0">
    <h2>My pools</h2>
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't created any pools!" if @mypools.empty? %></em></small></span>
    <% @mypools.each do |pool| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card-pool">
          <img src="<%= cl_image_path pool.photo.key, height: 300, crop: :fill unless pool.photo.key.blank?%>" />
          <div class="card-pool-infos">
            <div>
              <h2><%= pool.title %></h2>
              <p><%= pool.description %></p>
            </div>
            <div class="price-and-dropdown">
            <h2 class="card-pool-pricing">£<%= pool.price %></h2>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton<%= pool.id %>" data-bs-toggle="dropdown" aria-expanded="false">
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton<%= pool.id %>">
                <li> <%= link_to "View", pool_path(pool), class: "dropdown-item" %> </li>
                <li><a class="dropdown-item" href="<%= edit_pool_path(pool) %>">Edit</a></li>
                <li><%= link_to "Delete", pool_path(pool), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "dropdown-item" %></li>
              </ul>
            </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pools/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="form mary rounded p-3 shadow">
        <h3>List a Pool:</h3>
        <%= simple_form_for @pool do |f| %>
          <%= f.input :title, placeholder: 'Your pool name' %>
          <%= f.input :description, placeholder: 'Describe your pool', hint: 'Min 16 characters.' %>
          <%= f.input :address, placeholder: 'Your pool address' %>
          <div class="row">
            <div class="col-6">
              <%= f.input :price, as: :float, hint: 'eg. 89.59', label: 'Price per hour' %>
            </div>
            <div class="col-6">
              <%= f.input :capacity, collection: 1..20 %>
            </div>
          </div>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn-form' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pools/show.html.erb
<div class="container show-container">
  <div class="container-title">
    <h1><%= @pool.title %></h1>
    <h3>Price per hour: <strong>£<%= '%.2f' % @pool.price %></strong></h3>
  </div>
  <div class=container-img>
    <img src="<%= cl_image_path @pool.photo.key, height: 300, crop: :fill unless @pool.photo.key.blank?%>" />
    <div style="width: 600px; height: 400px;" id="map"
      data-controller="map"
      data-map-marker-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>


<div class="container-details">
  <div class= card-text>
    <div class="col">
    <p><%= @pool.description %></p>
    <p><strong><%= @pool.address %></strong></p>

  </div>

  <div class= "card-btn">
    <div class="col">
      <h6><strong>Capacity:</strong> <%= @pool.capacity %> people</h6>
      <%= link_to "Book pool", new_pool_booking_path, class: "btn btn-success" %>
      <%= link_to "Back to search", pools_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

  <div class="reviewheader">
  <h4><strong>All reviews:</strong>
  <% average_rating = @pool.reviews.average(:rating)&.round(2) || 0.0 %>
  <% if average_rating > 0.0 %>
    <i class="fas fa-star star-blue"></i><small><%= average_rating %></small>
  <%end%>
  </h4></div>

  <div class="container-review">
    <%= render 'shared/review_card' %>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="form mary rounded p-3 shadow">
      <h2>Your Review</h2>
        <%= simple_form_for([@booking, @review]) do |f| %>
          <%= f.input :title, placeholder: "Give your review a title..." %>
          <%= f.input :content, placeholder: "Add your review here..." %>
          <%= f.input :rating, :collection => 0..5, required: true, prompt: "What's your rating?" %>
          <%= f.button :submit, class: 'btn-form' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<%= render "form", review: @review %>

app/views/reviews/new.html.erb
<%= simple_form_for([@booking, @review]) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :rating, :collection => 0..5 %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_booking_card.html.erb
  <% bookings.each do |booking| %>
    <div class="col-12 col-sm-6 col-md-4 col-lg-4">
      <div class="card-pool">
        <img src="<%= cl_image_path booking.pool.photo.key, height: 300, crop: :fill unless booking.pool.photo.key.blank?%>" />
        <div class="card-pool-infos">
          <div>
            <h2><%= booking.user.first_name %> <%= booking.user.last_name %></h2>
            <p>Booked for: <strong><%= booking.pool.title %> </strong></p>
            <p>Start time: <%= booking.start_time.strftime("%B %d, %Y %I:%M %p") %></p>
            <p>End time: <%= booking.end_time.strftime("%B %d, %Y %I:%M %p") %></p>
          </div>
          <% if booking.status != "accepted" %>
            <div class="accept-reject-buttons">
              <h2 class="card-pool-pricing">Bill: £<%= '%.2f' % ((booking.pool.price / 60) * ((booking.end_time - booking.start_time) / 60)).round(2) %></h2>
              <div class="buttons-section">
                <small><%= button_to "Accept", update_booking_status_path(booking, status: 'accepted'), class: "booking-card-accept", method: :patch, data: {turbo: false} %></small>
                <small><%= button_to "Reject", update_booking_status_path(booking, status: 'rejected'), class: "booking-card-reject", method: :patch, data: {turbo: false} %></small>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-content">
    <div class="footer-left">
      <a href="/contact">Contact</a>
      <a href="/about_us">About us</a>
    </div>
    <div class="footer-right">
      <a href="https://tiktok.com" target="_blank"><i class="fab fa-tiktok"></i></a>
      <a href="https://instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag "AirPnP.png", class: "img-responsive", alt: "logo"%>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="col-sm-20 my-3 ">
      <%= form_with url: pools_path, method: :get, class: "d-flex flex-row flex-nowrap align-items-center" do %>
        <%= text_field_tag :location,
              params[:location],
              class: "form-control",
              placeholder: "Location..",
              style: "width: 350px; border-radius: 10px; height: 40px; margin: 5px"
          %>
          <div class="capacity-icon"><i class="fa-solid fa-users"></i></div>
        <%= text_field_tag :capacity,
              params[:capacity],
              class: "form-control form-control-sm",
              placeholder: "Capacity",
              style: "width: 75px; border-radius: 10px; height: 40px;"
          %>
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i>
        </button>
      <% end %>
    </div>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <a class="nav-link" href="<%= root_path %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://cdn-icons-png.flaticon.com/512/177/177667.png" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My pools", my_pools_path, class: "dropdown-item" %>
              <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%= link_to "Edit details", edit_user_registration_path, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pool_card.html.erb
<div class="row g-0">
  <% @pools.each do |pool| %>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      <%= link_to pool_path(pool) do %>
        <div class="card-pool">
          <img src="<%= cl_image_path pool.photo.key, height: 300, crop: :fill unless pool.photo.key.blank?%>" />
          <div class="card-pool-infos">
            <div class="title-description">
              <h2><%= pool.title %></h2>
              <p><%= pool.description %></p>
            </div>
            <div class="price-capacity">
              <div class="capacity-icon"><i class="fa-solid fa-users"></i><h2 class="card-pool-capacity"><%= pool.capacity %></h2></div>
              <h2 class="card-pool-pricing">£<%= '%.2f' % pool.price %></h2>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_review_card.html.erb
<% if @pool.reviews.present? %>
  <% @pool.reviews.each do |review| %>
    <div class="review-card">
      <div class="review-header">
        <div class="review-title"><%= review.title %></div>
        <div class="review-author-rating">
          <span class="review-author"><%= review.booking.user.first_name %> <%= review.booking.user.last_name %></span>
          <span class="review-rating">
            <% review.rating.times do %>
              <i class="fas fa-star star-blue"></i>
            <% end %>
          </span>
        </div>
      </div>
      <div class="review-content"> <p> <%= review.content %> <p> </div>
      <div class="review-post-time"><em> <%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></div>
    </div>
  <% end %>
<% else %>
  <p>Be the first one to review this pool!</p>
<% end %>